# day two of numpy

In [2]:
import numpy as np
months= np.array(["jan","feb","mar"])
months

array(['jan', 'feb', 'mar'], dtype='<U3')

In [3]:
import numpy as np

monthly_sales_array = np.array([
    [85, 90, 88],
    [76, 81, 79],
    [92, 95, 91],
    [68, 72, 70],
    [89, 84, 87],    
    [89, 84, 97], 
    [89, 94, 87]
    
])

In [4]:
agents = np.array(["Arun","Bala","Charan","Deepak","Esha","Farhan","Gokul"])
agents

array(['Arun', 'Bala', 'Charan', 'Deepak', 'Esha', 'Farhan', 'Gokul'],
      dtype='<U6')

In [5]:
monthly_sales_array

array([[85, 90, 88],
       [76, 81, 79],
       [92, 95, 91],
       [68, 72, 70],
       [89, 84, 87],
       [89, 84, 97],
       [89, 94, 87]])

In [8]:
# find the agent who topped in a jan, feb, march
print(dict(zip(months, agents[np.argmax(monthly_sales_array, axis=0)])))

{'jan': 'Charan', 'feb': 'Charan', 'mar': 'Farhan'}


In [12]:
index = np.argmax(monthly_sales_array, axis=0)
print(months, agents[index])

['jan' 'feb' 'mar'] ['Charan' 'Charan' 'Farhan']


In [17]:
# find  the agent who performed above average in every month
monthly_average = np.mean(monthly_sales_array, axis=0)
monthly_average

array([84.        , 85.71428571, 85.57142857])

In [18]:
monthly_sales_array > monthly_average

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False],
       [ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [25]:
agents[...] #... or _ means  the previous cells output

array(['Arun', 'Bala', 'Charan', 'Deepak', 'Esha', 'Farhan', 'Gokul'],
      dtype='<U6')

In [26]:
average = np.mean(monthly_sales_array, axis=0)
print(agents[np.all(monthly_sales_array > monthly_average, axis=1)])

['Arun' 'Charan' 'Gokul']


In [29]:
a= np.random.randint(200,700,(5,5))
a


array([[411, 627, 202, 534, 330],
       [443, 679, 598, 434, 533],
       [394, 664, 593, 556, 544],
       [205, 543, 391, 302, 210],
       [535, 582, 261, 595, 518]])

In [35]:
b = np.random.randint(700,900,(5))
b+a

array([[1237, 1372, 1006, 1250, 1180],
       [1269, 1424, 1402, 1150, 1383],
       [1220, 1409, 1397, 1272, 1394],
       [1031, 1288, 1195, 1018, 1060],
       [1361, 1327, 1065, 1311, 1368]])

In [37]:
c= np.random.randint(7000, 8000, (1,5))
c

array([[7576, 7084, 7902, 7441, 7814]])

In [39]:
b+c

array([[8402, 7829, 8706, 8157, 8664]])

### broadcasting rule 1:

if two arrays are of the same dimension, if one of the dimension in an array is 1 and other dimension match exactly in both arrays, broadcasting can happen 


fpr examle:

if A is a 5*5 matrix and B is a 1*5 matrix. the matrix b is broadcasted to 5*5 to match the shape of A

id A is a 6*5 matrix and B is a 2*5 matrix, yhe matrix B couldnt be broadcasted to 585 to match the shape of A as one of the dimensions  i not exactly  1. it voilates rule  1

In [41]:
s = np.random.randint(7000, 8000, (5,5))
s

array([[7431, 7855, 7339, 7236, 7061],
       [7865, 7718, 7172, 7637, 7036],
       [7251, 7293, 7486, 7237, 7327],
       [7178, 7018, 7867, 7051, 7649],
       [7259, 7912, 7886, 7640, 7741]])

In [43]:
r = np.random.randint(500, 700, (1,5))
r

array([[532, 600, 575, 636, 619]])

In [44]:
s+r

array([[7963, 8455, 7914, 7872, 7680],
       [8397, 8318, 7747, 8273, 7655],
       [7783, 7893, 8061, 7873, 7946],
       [7710, 7618, 8442, 7687, 8268],
       [7791, 8512, 8461, 8276, 8360]])

In [45]:
p = np.random.randint(500, 700, (5,1))
p

array([[578],
       [514],
       [599],
       [513],
       [553]])

In [46]:
s+p

array([[8009, 8433, 7917, 7814, 7639],
       [8379, 8232, 7686, 8151, 7550],
       [7850, 7892, 8085, 7836, 7926],
       [7691, 7531, 8380, 7564, 8162],
       [7812, 8465, 8439, 8193, 8294]])

In [ ]:
import numpy as np

print("="*70)
print("NUMPY BROADCASTING - COMPLETE CHEAT SHEET")
print("="*70)

# ----------------------------------------------------
# Rule 1: Same Shape
# ----------------------------------------------------
print("\nRule 1: Same Shape")
a = np.array([1,2,3])
b = np.array([10,20,30])

print("Shape:", a.shape, b.shape)
print(a+b)

# ----------------------------------------------------
# Rule 2: Scalar Broadcasting
# ----------------------------------------------------
print("\nRule 2: Scalar Broadcasting")
a = np.array([[1,2],[3,4]])

print(a)
print(a+10)

# ----------------------------------------------------
# Rule 3: Row Broadcasting
# ----------------------------------------------------
print("\nRule 3: Row Broadcasting")

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print("Shapes:", a.shape, b.shape)
print(a+b)

# ----------------------------------------------------
# Rule 4: Column Broadcasting
# ----------------------------------------------------
print("\nRule 4: Column Broadcasting")

a = np.array([[1],
              [2],
              [3]])

b = np.array([10,20,30])

print("Shapes:", a.shape, b.shape)
print(a+b)

# ----------------------------------------------------
# Rule 5: 2D + 2D
# ----------------------------------------------------
print("\nRule 5: Same 2D Shape")

a = np.array([[1,2],
              [3,4]])

b = np.array([[10,20],
              [30,40]])

print(a+b)

# ----------------------------------------------------
# Rule 6: Broadcasting Error
# ----------------------------------------------------
print("\nRule 6: Error Example")

a = np.array([1,2,3])
b = np.array([10,20])

print("Shapes:", a.shape, b.shape)

try:
    print(a+b)
except Exception as e:
    print("Error:", e)

# ----------------------------------------------------
# Rule 7: Reshape to Fix Broadcasting
# ----------------------------------------------------
print("\nRule 7: Fix Using reshape")

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20]).reshape(2,1)

print("Shapes:", a.shape, b.shape)
print(a+b)

# ----------------------------------------------------
# Rule 8: Real World Example (Monthly Bonus)
# ----------------------------------------------------
print("\nRule 8: Employee Monthly Bonus")

sales = np.array([
    [100,200,300],
    [150,250,350],
    [180,280,380]
])

bonus = np.array([10,20,30])

print("Original Sales")
print(sales)

print("\nBonus")
print(bonus)

print("\nAfter Bonus")
print(sales+bonus)

# ----------------------------------------------------
# Rule 9: Salary Increment
# ----------------------------------------------------
print("\nRule 9: Salary Increment")

salary = np.array([30000,40000,50000])

print(salary+5000)

# ----------------------------------------------------
# Rule 10: Broadcasting Conditions
# ----------------------------------------------------
print("\nBroadcasting Rules")
print("1. Compare shapes from RIGHT to LEFT")
print("2. Dimensions must be Equal OR one of them must be 1")
print("3. Missing dimension is treated as 1")
print("4. Otherwise -> ValueError")

print("\nExamples")
print("(3,)  + (3,)   -> Works")
print("(3,3) + (3,)   -> Works")
print("(3,1) + (3,)   -> Works")
print("(2,3) + (2,1)  -> Works")
print("(3,)  + (2,)   -> Error")
print("(2,3) + (2,)   -> Error")