# Numpy

The core object in numpy is **ndarray**

## Creating 1d array in numpay 

In [3]:
import numpy as np

In [4]:
np.array?


Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [5]:
sales = [230, 440, 550, 650,700]
sales_array = np.array(sales)

In [6]:
type(sales_array)

numpy.ndarray

In [7]:
print(sales_array)

[230 440 550 650 700]


In [8]:
no_sales = np.array([220, 500, "na"])
print(no_sales)

['220' '500' 'na']


In [10]:
no_sales_nan = np.array([200, 300, 700, np.nan])

In [11]:
no_sales_nan = no_sales_nan.astype('float16')

In [12]:
no_sales_nan.dtype

dtype('float16')

In [14]:
no_sales_nan.mean() # it wont work ndue to place of nan

nan

In [15]:
np.nanmean(no_sales_nan)  #outputs

400.0

In [21]:
# repace the element withe 500
no_sales_nan[0]= 500

In [23]:
no_sales_nan

array([500., 300., 700.,  nan], dtype=float16)

## indexing in 1D array 

In [34]:
sales_array

array([230, 440, 550, 650, 700])

In [25]:
agents= np.array(["raj", "sam", "ram", "eram"])
agents

array(['raj', 'sam', 'ram', 'eram'], dtype='<U4')

In [27]:
#find the sales count made by eram
eram_idx= np.where(agents == "eram")[0][0]
eram_idx

3

In [28]:
sales[eram_idx]

650

In [31]:
# find the sales (count) made by kumar  
sam_idx = np.where(agents=="sam")[0][0]
sam_idx

1

In [32]:
sales[sam_idx]

440

In [39]:
sales_array.argmax() # it outputs the index of the max sales 

4

In [42]:
max_sal = sales_array.argmax()
agents[max_sal]

IndexError: index 4 is out of bounds for axis 0 with size 4

# slicing 1d Arrays

In [43]:
#find the agents who did above average sales 
alicing_array= np.array([200,500,600,700,800,1000])
alicing_array

array([ 200,  500,  600,  700,  800, 1000])

In [45]:
names = np.array([
    "Arun",
    "Bala",
    "Charan",
    "Deepak",
    "Esha",
    "Farhan"
])
names

array(['Arun', 'Bala', 'Charan', 'Deepak', 'Esha', 'Farhan'], dtype='<U6')

In [48]:
avg = np.mean(alicing_array)
print(avg)

633.3333333333334


In [49]:
above_avg = np.where(alicing_array > avg)
names[above_avg]

array(['Deepak', 'Esha', 'Farhan'], dtype='<U6')

In [50]:
#fancy indexing we can use it where the we need to take ununiformed indexed array
names[[0,3,5,2]]

array(['Arun', 'Deepak', 'Farhan', 'Charan'], dtype='<U6')

In [51]:
# find the top 5 performing agents or names by sales
# sort the sales in desc
#slice the top
#index it against the agents or name 

In [52]:
import numpy as np

agents = np.array([
    "Arun", "Bala", "Charan", "Deepak",
    "Esha", "Farhan", "Gokul", "Hari"
])

sales = np.array([450, 800, 600, 1200, 700, 950, 500, 1100])

In [54]:
sorted_index = np.argsort(sales)[::-1]
sorted_index

array([3, 7, 5, 1, 4, 2, 6, 0], dtype=int64)

In [56]:
top5_index = sorted_index[:5]
top5_index

array([3, 7, 5, 1, 4], dtype=int64)

In [57]:
top5_agents = agents[top5_index]
print(top5_agents)

['Deepak' 'Hari' 'Farhan' 'Bala' 'Esha']


In [58]:
top5_sales = sales[top5_index]
print(top5_sales)

[1200 1100  950  800  700]


In [59]:
#shotest and fasted approach
top5_index = np.argsort(sales)[::-1][:5]

print(agents[top5_index])
print(sales[top5_index])

['Deepak' 'Hari' 'Farhan' 'Bala' 'Esha']
[1200 1100  950  800  700]


In [63]:
last5_index = np.argsort(sales)[:5]

print(agents[last5_index])
print(sales[last5_index])

['Arun' 'Gokul' 'Charan' 'Esha' 'Bala']
[450 500 600 700 800]


In [64]:
sales.ndim

1

# creating 2d array 

for creating 1d array we gave a list as input to the np.array() function 


for creating 2d array we should give list of list to the np.array() fuction 

In [67]:
monthly_sales =[[
    [85, 90, 88],
    [76, 81, 79],
    [92, 95, 91],
    [68, 72, 70],
    [89, 84, 87],    
    [89, 84, 97], 
    [89, 94, 87]
]]

In [73]:
import numpy as np

monthly_sales_array = np.array([
    [85, 90, 88],
    [76, 81, 79],
    [92, 95, 91],
    [68, 72, 70],
    [89, 84, 87],    
    [89, 84, 97], 
    [89, 94, 87]
    
])

In [66]:
monthly_sales.ndim

2

In [69]:
agents = np.array(["Arun","Bala","Charan","Deepak","Esha","Farhan","Gokul"])
agents

array(['Arun', 'Bala', 'Charan', 'Deepak', 'Esha', 'Farhan', 'Gokul'],
      dtype='<U6')

In [75]:
monthly_sales_array.shape # outputs the number of rows and coloumns in a tuple form

(7, 3)

In [77]:
# other ways to create 2d arrays 
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [78]:
arr = np.random.randint(100, 251, size=(5, 5))
print(arr)

[[227 127 158 100 143]
 [179 144 240 148 246]
 [170 133 176 173 179]
 [216 172 137 247 136]
 [121 147 121 236 160]]


In [79]:
arr.shape

(5, 5)

In [80]:
# idntitdy matrix, square matrix(rows = coloums) wuth a number 1 at the diagonal 
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [86]:
arr2=np.eye(3)           #n represents the number of rows . n=m in a square matrix
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
arr2=np.eye(3,k=1)
arr2#n represents the number of rows . n=m in a square matrix


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [92]:
#create a 5x8 matrix with all zeros 
arr3 = np.zeros((5, 8), dtype=int)
arr3

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [95]:
#create a 3x5 matrix with all values 100
np.full((3,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [98]:
months= np.array(["jan","feb","mar"])
months

array(['jan', 'feb', 'mar'], dtype='<U3')

In [99]:
monthly_sales

array([[85, 90, 88],
       [76, 81, 79],
       [92, 95, 91],
       [68, 72, 70],
       [89, 84, 87],
       [89, 84, 97],
       [89, 94, 87]])

In [100]:
agents

array(['Arun', 'Bala', 'Charan', 'Deepak', 'Esha', 'Farhan', 'Gokul'],
      dtype='<U6')

In [125]:
#find bala's jan salary.
print(monthly_sales[np.where(agents == "Bala")[0][0], 0])

76


In [105]:
y = np.random.randint(100, 500, (3,4))


array([[226, 377, 448, 201],
       [479, 168, 117, 463],
       [264, 269, 438, 287]])

In [106]:
y[0]

array([226, 377, 448, 201])

In [109]:

y[0:1]


array([[226, 377, 448, 201]])

In [112]:

y[:, [0,1]]


array([[226, 377],
       [479, 168],
       [264, 269]])

In [116]:
y[[0, 2], [2, 3]]

array([448, 287])

In [119]:
y[1,3]

463

In [120]:
y[[0,1],[1,3]]

array([377, 463])

In [127]:
index = np.where(agents == "Deepak")[0][0]

jan_sales = monthly_sales[index, 2]

print(jan_sales)

70


In [139]:
index = np.where(agents == "Farhan")[0][0]
monthly_sales[index, 0] = 196

In [140]:
monthly_sales

array([[ 85,  90,  88],
       [ 76,  81,  79],
       [ 92,  95,  91],
       [ 68,  72,  70],
       [ 89,  84,  87],
       [196,  84,  97],
       [ 89,  94,  87]])

In [141]:
#find the agent who topped in sales in january 
#slice the jan sales and use argmax()
#index against agents
jan_inx = np.where(months =="jan")[0][0]
jan_inx


0

In [142]:
monthly_sales_array[:,jan_inx]

array([85, 76, 92, 68, 89, 89, 89])

In [146]:
r= monthly_sales_array[:,jan_inx].argmax()

In [149]:
ind = agents[r]
ind

'Charan'

In [153]:
total_sales = np.sum(monthly_sales, axis=1)

least_index = np.argmin(total_sales)

print("Agent:", agents[least_index])
print("Total Sales:", total_sales[least_index])

Agent: Deepak
Total Sales: 210


In [159]:
# Find Esha's row
index = np.where(agents == "Esha")[0][0]

# Find the month index with maximum sales
max_sale = np.argmax(monthly_sales[index])

print("Month:", months[max_sale])
print("Month Index:", max_sale)

Month: jan
Month Index: 0
